### PR TITLE
feat(icon): add buildings icon

### PR DESCRIPTION
**Pull request by thisguyscode**

### CODE REVIEW

**Comment by thisguyscode** [comment]
@SamCreasey and @SamuelAlev - Added you as reviewers as you're the ones using this icon anyway, so kill two birds with one stone (notify you and get it reviewed ;) )

**Comment by thisguyscode** [comment]
Hmmm, I just noticed that various Caret icons got generated too. I know they're used in the DatePicker which is already merged, so not sure what's going on there. Do you?

**Comment by SamuelAlev** [comment]
They just never ran `npm run build` but the CI does it so it is still bundled

**Comment by thisguyscode** [comment]
> They never ran `npm run build` but the CI does it so it is still bundled

@SamuelAlev  So it's okay or should I also not run build?

**Review by SamuelAlev — APPROVED** [review]

**Pull request merged**
